---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "headscale.fullname" . }}-config
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{ .Values.headscale.config | toYaml | nindent 4 }}
  {{- if .Values.headscale.derp }}
  derp.yaml: |-
    {{ .Values.headscale.derp | toYaml | nindent 4 }}
  {{- end }}
