{{ if eq .Values.headscale.db.type "sqlite3" }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "headscale.fullname" . }}
  labels:
    {{- include "headscale.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "headscale.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "headscale.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "headscale.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "headscale.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{ if .Values.headscale.debug }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}-debug"
          {{ else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- end }}
          command: ["headscale"]
          args: ["serve"]
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- with .Values.nodeSelector }}
          nodeSelector:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.affinity }}
          affinity:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          {{- with .Values.tolerations }}
          tolerations:
            {{- toYaml . | nindent 8 }}
          {{- end }}
          env:
            - name: HEADSCALE_SERVER_URL
              value: {{ .Values.headscale.server_url }}
            - name: HEADSCALE_LISTEN_ADDR
              value: "{{ .Values.headscale.listen_addr }}"
            - name: HEADSCALE_METRICS_LISTEN_ADDR
              value: "{{ .Values.headscale.metrics_listen_addr }}"
          {{ if .Values.headscale.private_key }}
            - name: HEADSCALE_PRIVATE_KEY_PATH
              value: /private-key/private-key
          {{ else }}
            - name: HEADSCALE_PRIVATE_KEY_PATH
              value: /data/private-key
          {{ end }}
            - name: HEADSCALE_DERP_MAP_PATH
              value: /config/derp.yaml
            - name: HEADSCALE_EPHEMERAL_NODE_INACTIVITY_TIMEOUT
              value: {{ .Values.headscale.ephemeral_node_inactivity_timeout }}
            - name: HEADSCALE_DB_TYPE
              value: {{ .Values.headscale.db.type }}
            - name: HEADSCALE_DB_PATH
              value: {{ .Values.headscale.db.path }}
            - name: HEADSCALE_LOG_LEVEL
              value: {{ .Values.headscale.log_level }}
          ports:
            - name: http
              containerPort: {{ include "split-host-port" .Values.headscale.listen_addr }}
              protocol: TCP
            - name: metrics
              containerPort: {{ include "split-host-port" .Values.headscale.metrics_listen_addr }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.headscale.grpc.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: http
          volumeMounts:
            - name: {{ include "headscale.fullname" . }}-data
              mountPath: /data
      {{ if .Values.headscale.private_key }}
            - name: private-key
              mountPath: /private-key
      {{ end }}
            - name: derp
              mountPath: /config/
      volumes:
      {{ if .Values.headscale.private_key }}
      {{ if .Values.headscale.private_key.key  }}
      - name: private-key
        secret:
          secretName: {{ include "headscale.fullname" . }}-key
      {{ end }}
      {{ if .Values.headscale.private_key.existing_secret }}
      - name: private-key
        secret:
          secretName: {{ .Values.headscale.private_key.existing_secret }}
      {{ end }}
      {{ end }}
      - name: derp
        configMap:
          name: {{ include "headscale.fullname" .}}-derp
  volumeClaimTemplates:
  - metadata:
      name: {{ include "headscale.fullname" . }}-data
    spec:
      storageClassName: {{ .Values.storage.class }}
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: {{ .Values.storage.size }}
{{ end }}
